import { useState } from "react";
import { Icon } from "./Icon";
import { ClientSearch } from "./ClientSearch";
import { competenceLabel, dateInputValue } from "../utils/dates";
import type { Field, Row } from "../types";

type Props = { fields: Field[]; selectedRow: Row | null; lookups: Record<string, Row[]>; editing: boolean; onCreatePerson?: (values: Row) => Promise<Row> };
function PersonRoles({ selectedRow }: Pick<Props, "selectedRow">) { return <fieldset className="role-field full-field"><legend>Esta pessoa é</legend><div className="role-options">{[["cliente", "Cliente", "Compra produtos ou serviços"], ["fornecedor", "Fornecedor", "Fornece produtos ou serviços"]].map(([name, label, hint]) => <label className="role-choice" key={name}><input type="checkbox" name={name} defaultChecked={Boolean(selectedRow?.[name])} /><span className="custom-check"><Icon name="check" size={13} /></span><span><b>{label}</b><small>{hint}</small></span></label>)}</div></fieldset>; }
function SelectField({ field, selectedRow, lookups, editing }: Omit<Props, "fields"> & { field: Field }) { return <select name={field.name} required={field.required} disabled={editing && field.name === "lancamento_id"} defaultValue={String(selectedRow?.[field.name] ?? "")}><option value="">{field.required ? "Selecione uma opção" : "Não selecionado"}</option>{field.options?.map(([value, label]) => <option key={value} value={value}>{label}</option>)}{field.source && (lookups[field.source] || []).map((item) => <option key={String(item.id)} value={String(item.id)}>{String(item.nome || item.descricao || item.id)}</option>)}</select>; }
function InputField({ field, selectedRow }: Pick<Props, "selectedRow"> & { field: Field }) { const isInstallment = field.name === "parcelas"; const isNumber = field.type === "number"; return <><input name={field.name} type={field.type || "text"} required={field.required} step={isInstallment ? "1" : isNumber ? "0.01" : undefined} min={isInstallment ? "1" : isNumber ? "0.01" : undefined} max={isInstallment ? "60" : undefined} maxLength={isNumber || field.type === "date" ? undefined : 200} defaultValue={field.type === "date" ? dateInputValue(selectedRow?.[field.name]) : String(selectedRow?.[field.name] ?? (isInstallment ? "1" : ""))} placeholder={isInstallment ? "1" : isNumber ? "0,00" : field.type === "date" ? "" : `Informe ${field.label.toLowerCase()}`} />{isInstallment && <small className="field-hint">1 para à vista. No parcelamento simples, o intervalo padrão é de 30 dias.</small>}</>; }
export function RecordFormFields({ fields, selectedRow, lookups, editing, onCreatePerson }: Props) {
    const launch = fields.some((field) => field.name === "parcelas");
    const isLancamento = launch && !editing;
    const [due, setDue] = useState(dateInputValue(selectedRow?.data_vencimento));
    const [competence, setCompetence] = useState(competenceLabel(selectedRow?.competencia || selectedRow?.data_vencimento));
    const [mode, setMode] = useState("total"); const [detailed, setDetailed] = useState(false);
    return <div className="form-grid">{fields.filter((field) => !(editing && field.name === "parcelas") && !(field.type === "checkbox" && field.name === "fornecedor") && !(launch && field.name === "banco_id")).map((field) => {
        if (field.type === "checkbox") return <PersonRoles key={field.name} selectedRow={selectedRow} />;
        if (launch && field.name === "pessoa_id") return <ClientSearch key={field.name} selectedRow={selectedRow} rows={lookups.pessoas || []} onCreate={onCreatePerson} />;
        return <label key={field.name} className={`form-field ${field.wide ? "full-field" : ""}`}>{field.name === "valor" && isLancamento ? mode === "total" ? "Valor total da operação" : "Valor de cada parcela" : field.label}
            {launch && field.name === "data_vencimento" ? <input name={field.name} type="date" required value={due} onChange={event => { setDue(event.target.value); setCompetence(competenceLabel(event.target.value)); }} />
            : field.name === "competencia" ? <><input name={field.name} value={competence} required={field.required} placeholder="out/2026" pattern="(jan|fev|mar|abr|mai|jun|jul|ago|set|out|nov|dez)/[0-9]{4}" title="Informe mês/ano, por exemplo out/2026" onChange={event => setCompetence(event.target.value.toLowerCase())} /><small className="field-hint">Mês/ano. Pode ser diferente do vencimento.</small></>
            : field.type === "select" ? <SelectField field={field} selectedRow={selectedRow} lookups={lookups} editing={editing} /> : <InputField field={field} selectedRow={selectedRow} />}</label>;
    })}
        {isLancamento && <fieldset className="installment-options full-field"><legend>Parcelamento</legend><div className="value-mode"><label><input type="radio" name="modo_valor" value="total" checked={mode === "total"} onChange={() => setMode("total")} /> Informar valor total</label><label><input type="radio" name="modo_valor" value="parcela" checked={mode === "parcela"} onChange={() => setMode("parcela")} /> Informar valor de cada parcela</label></div><label className="detail-toggle"><input type="checkbox" name="detalhar_parcelamento" checked={detailed} onChange={(event) => setDetailed(event.target.checked)} /> Detalhar parcelamento</label>{detailed && <div className="detail-installments"><small>Informe os dias até cada parcela. Ex.: 15, 30, 45 para 15/15/15 dias.</small><input name="intervalos" placeholder="15, 30, 45" required={detailed} /></div>}</fieldset>}</div>;
}
