import { useState } from "react";
import { Icon } from "./Icon";
import type { Field, Row } from "../types";

type Props = { fields: Field[]; selectedRow: Row | null; lookups: Record<string, Row[]>; editing: boolean };
function PersonRoles({ selectedRow }: Pick<Props, "selectedRow">) { return <fieldset className="role-field full-field"><legend>Esta pessoa é</legend><div className="role-options">{[["cliente", "Cliente", "Compra produtos ou serviços"], ["fornecedor", "Fornecedor", "Fornece produtos ou serviços"]].map(([name, label, hint]) => <label className="role-choice" key={name}><input type="checkbox" name={name} defaultChecked={Boolean(selectedRow?.[name])} /><span className="custom-check"><Icon name="check" size={13} /></span><span><b>{label}</b><small>{hint}</small></span></label>)}</div></fieldset>; }
function SelectField({ field, selectedRow, lookups }: Omit<Props, "fields" | "editing"> & { field: Field }) { return <select name={field.name} required={field.required} defaultValue={String(selectedRow?.[field.name] ?? "")}><option value="">{field.required ? "Selecione uma opção" : "Não selecionado"}</option>{field.options?.map(([value, label]) => <option key={value} value={value}>{label}</option>)}{field.source && (lookups[field.source] || []).map((item) => <option key={String(item.id)} value={String(item.id)}>{String(item.nome || item.descricao || item.id)}</option>)}</select>; }
function InputField({ field, selectedRow, valueLabel }: Pick<Props, "selectedRow"> & { field: Field; valueLabel?: string }) { const isInstallment = field.name === "parcelas"; const isNumber = field.type === "number"; return <><input name={field.name} type={field.type || "text"} required={field.required} step={isInstallment ? "1" : isNumber ? "0.01" : undefined} min={isInstallment ? "1" : isNumber ? "0.01" : undefined} max={isInstallment ? "60" : undefined} maxLength={isNumber || field.type === "date" ? undefined : 200} defaultValue={String(selectedRow?.[field.name] ?? (isInstallment ? "1" : ""))} placeholder={isInstallment ? "1" : isNumber ? "0,00" : field.type === "date" ? "" : `Informe ${(valueLabel || field.label).toLowerCase()}`} />{isInstallment && <small className="field-hint">1 para à vista. No parcelamento simples, o intervalo padrão é de 30 dias.</small>}</>; }
export function RecordFormFields({ fields, selectedRow, lookups, editing }: Props) {
    const isLancamento = fields.some((field) => field.name === "parcelas") && !editing;
    const [mode, setMode] = useState("total"); const [detailed, setDetailed] = useState(false);
    return <div className="form-grid">{fields.filter((field) => !(editing && field.name === "parcelas") && !(field.type === "checkbox" && field.name === "fornecedor") && !(isLancamento && field.name === "banco_id")).map((field) => field.type === "checkbox" ? <PersonRoles key={field.name} selectedRow={selectedRow} /> : <label key={field.name} className={`form-field ${field.wide ? "full-field" : ""}`}>{field.name === "valor" && isLancamento ? mode === "total" ? "Valor total da operação" : "Valor de cada parcela" : field.label}{field.type === "select" ? <SelectField field={field} selectedRow={selectedRow} lookups={lookups} /> : <InputField field={field} selectedRow={selectedRow} valueLabel={field.label} />}</label>)}
        {isLancamento && <fieldset className="installment-options full-field"><legend>Parcelamento</legend><div className="value-mode"><label><input type="radio" name="modo_valor" value="total" checked={mode === "total"} onChange={() => setMode("total")} /> Informar valor total</label><label><input type="radio" name="modo_valor" value="parcela" checked={mode === "parcela"} onChange={() => setMode("parcela")} /> Informar valor de cada parcela</label></div><label className="detail-toggle"><input type="checkbox" name="detalhar_parcelamento" checked={detailed} onChange={(event) => setDetailed(event.target.checked)} /> Detalhar parcelamento</label>{detailed && <div className="detail-installments"><small>Informe os dias até cada parcela. Ex.: 15, 30, 45 para 15/15/15 dias.</small><input name="intervalos" placeholder="15, 30, 45" required={detailed} /></div>}</fieldset>}</div>;
}